version: "3.9"

services:
  # these are the recommended settings to run your app
  drawapp:
    image: gitlab-container.tba-hosting.de/lpa-aflek-alice/excalidraw-lti-application:latest
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./data:/srv/data
      - ./media:/srv/media
      - ./deployment_settings.py:/srv/deployment_settings.py:ro
      - ./static:/srv/static_copy
    command: "draw.asgi --bind=0.0.0.0:8000"
    environment:
      - "DJANGO_SETTINGS_MODULE=deployment_settings"

  # maria:
  #   image: mariadb:latest
  #   environment:
  #     - MARIADB_DATABASE=draw
  #     - MARIADB_USER=draw
  #     - MARIADB_PASSWORD=drawpass666
  #   volumes:
  #     - './mariadb:/var/lib/mysql'

  # redis:
  #   image: redis:alpine
  #   volumes:
  #     - ./redis/data:/data
  #     - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
