# Generated by Django 3.2.12 on 2022-02-21 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcalidrawLogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_compressed', models.BooleanField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_name', models.CharField(max_length=24, validators=[django.core.validators.MinLengthValidator(24)])),
                ('event_type', models.CharField(max_length=50)),
                ('user_pseudonym', models.CharField(help_text='this is geenrated from ltiapi.models.CustomUser.id_for_room', max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(40)])),
                ('_content', models.BinaryField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExcalidrawRoom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('room_name', models.CharField(max_length=24, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(24)])),
                ('_elements', models.BinaryField(blank=True, default=b'x\x9c\x8b\x8e\x05\x00\x01\x15\x00\xb9')),
            ],
        ),
    ]
