# Generated by Django 3.2.12 on 2022-02-17 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excalidrawlogrecord',
            name='user_pseudonym',
            field=models.CharField(help_text='this is geenrated from ltiapi.models.CustomUser.id_for_room', max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(40)]),
        ),
        migrations.AlterField(
            model_name='excalidrawroom',
            name='_elements',
            field=models.BinaryField(blank=True, default=b'x\x9c\x8b\x8e\x05\x00\x01\x15\x00\xb9'),
        ),
    ]
