# Generated by Django 3.2.12 on 2022-03-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0002_auto_20220228_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='excalidrawroom',
            name='room_course_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
