# Generated by Django 3.2.12 on 2022-03-02 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_excalidrawroom_room_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excalidrawlogrecord',
            name='user_pseudonym',
            field=models.CharField(help_text='this is generated from ltiapi.models.CustomUser.id_for_room', max_length=64, null=True, validators=[django.core.validators.MinLengthValidator(64)]),
        ),
    ]
