# Generated by Django 3.2.12 on 2022-03-29 13:49

from django.db import migrations, models
import draw.utils


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0005_excalidrawfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excalidrawlogrecord',
            name='room_name',
            field=models.CharField(max_length=24, validators=[draw.utils.validate_room_name]),
        ),
        migrations.AlterField(
            model_name='excalidrawroom',
            name='room_name',
            field=models.CharField(max_length=24, primary_key=True, serialize=False, validators=[draw.utils.validate_room_name]),
        ),
        migrations.AlterUniqueTogether(
            name='excalidrawfile',
            unique_together={('belongs_to', 'element_file_id')},
        ),
    ]
