# Generated by Django 4.0.4 on 2022-08-24 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import draw.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lti1p3_tool_config', '0001_initial'),
        ('collab', '0006_auto_20220406_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excalidrawroom',
            name='room_consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lti1p3_tool_config.ltitool'),
        ),
        migrations.CreateModel(
            name='CourseToRoomMapper',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='collab.excalidrawroom', verbose_name='room name')),
                ('lti_data_room', models.CharField(max_length=24, validators=[draw.utils.validate_room_name])),
                ('mode', models.CharField(choices=[('classroom', 'Classroom Assignment'), ('group', 'Group Assignment'), ('single_v2', 'Single Student'), ('single', 'Single Student Assignment (legacy)')], default='classroom', max_length=12, verbose_name='board mode')),
                ('course_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'unique_together': {('lti_data_room', 'course_id', 'user')},
            },
        ),
    ]
