# Generated by Django 4.0.4 on 2023-06-19 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collab', '0008_excalidrawroom_tracking_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excalidrawroom',
            name='room_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
