# Generated by Django 3.2.12 on 2022-02-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool_config', '0001_initial'),
        ('ltiapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneoffregistrationlink',
            name='consumer_registration_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='consumer registration timestamp'),
        ),
        migrations.AlterField(
            model_name='oneoffregistrationlink',
            name='registered_consumer',
            field=models.OneToOneField(blank=True, help_text='only fills after registration completed', null=True, on_delete=django.db.models.deletion.CASCADE, to='lti1p3_tool_config.ltitool', verbose_name='registered consumer'),
        ),
    ]
